### ISSUE TITLE
Limite cantidad de decimales 

### ISSUE THREAD

**Issue by Bochincito** [Irwin1985/JSONFox#1]
Irwin. Muy buena tu clase.
La estoy usando junto con VFPRest (ambas tomadas de tus videos de EZP) para leer una API de google que dada una dirección me devuelve Latitud y Longitud en formato jSon.
El problema es que el DECODE de la respuesta me trae Latitud y Longitud pero solo con 6 decimales y me quita el signo negativo (para Latitud Sur por ejemplo).
Se podrá corregir??

**Comment by Bochincito** [comment]
Hola de nuevo, Irwin.
Estuve revisando el código y quiero corregir y mejorar mi issue anterior.
1) Lo de retornar solo 6 decimales era un error mio. Estaba tomando un dato que era en 6 decimales. Estaba mirando la propiedad equivocada. Perdon.
2) Lo de quitar el signo.  Tu asumes que al string que tienes le has quitado el signo, por lo que luego del VAL() si lo habias calificado como negativo lo multiplicas por (-1). Pero en realidad no se lo has quitado, por lo que al multiplicarlo en realidad lo vuelves positivo.
Perdon, no se como funciona GitHub, Se que hay una forma correcta de sugerir una corrección, pero no la conozco en este momento asi que lo hago aca. Comente tu línea y puse a continuación la que me ha funcionado bien.

	Hidden Procedure __parse_number As Number
		Local cNumber As String, bIsNegative As boolean
                .
                .
		nValNumber = Val(cNumber)
 		** Return Iif(bIsNegative, nValNumber * -1, nValNumber)
        RETURN nValNumber

Saludos

**Comment by Irwin1985** [comment]
Hola Bochincito te ha servido el cambio? para ponerlo en la clase y actualizarla. Gracias por el feed.
