### ISSUE TITLE
Feild having Large Content like QR code String not Parsing Properly

### ISSUE THREAD

**Issue by RightOpen** [Irwin1985/JSONFox#10]
`{
  "data": {
    "SignedInvoice": "eyJhbGciOiJSUzI1NiIsImtpZCI6IkVEQzU3REUxMzU4QjMwMEJBOUY3OTM0MEE2Njk2ODMxRjNDODUwNDciLCJ0eXAiOiJKV1QiLCJ4NXQiOiI3Y1Y5NFRXTE1BdXA5NU5BcG1sb01mUElVRWMifQ.eyJkYXRhIjoie1wiQWNrTm9cIjoxMzIxMTAwMjYzNjY1MjAsXCJBY2tEdFwiOlwiMjAyMS0wMi0yMyAxNzo0NzowMVwiLFwiSXJuXCI6XCIxOTg2ZGQwODJlZDM3ZmQ5YmVmNTQ5OGNhNjkxZTQzZWM1ZmNhNjBlMTlhZTI4MmRiMjVlZTA2YmVjZjVmYmQ3XCIsXCJWZXJzaW9uXCI6XCIxLjFcIixcIlRyYW5EdGxzXCI6e1wiVGF4U2NoXCI6XCJHU1RcIixcIlN1cFR5cFwiOlwiQjJCXCIsXCJSZWdSZXZcIjpcIllcIixcIklnc3RPbkludHJhXCI6XCJOXCJ9LFwiRG9jRHRsc1wiOntcIlR5cFwiOlwiSU5WXCIsXCJOb1wiOlwiTUFISS8xMFwiLFwiRHRcIjpcIjEwLzEwLzIwMjBcIn0sXCJTZWxsZXJEdGxzXCI6e1wiR3N0aW5cIjpcIjAzQUFBQ1Y4NzIyRDFaT1wiLFwiTGdsTm1cIjpcIkFCQyBjb21wYW55IHB2dCBsdGRcIixcIlRyZE5tXCI6XCJOSUMgSW5kdXN0cmllc1wiLFwiQWRkcjFcIjpcIjV0aCBibG9jaywga3V2ZW1wdSBsYXlvdXRcIixcIkFkZHIyXCI6XCJrdXZlbXB1IGxheW91dFwiLFwiTG9jXCI6XCJHQU5ESElOQUdBUlwiLFwiUGluXCI6MTQ0MDAzLFwiU3RjZFwiOlwiMDNcIixcIlBoXCI6XCI5MDAwMDAwMDAwXCIsXCJFbVwiOlwiYWJjQGdtYWlsLmNvbVwifSxcIkJ1eWVyRHRsc1wiOntcIkdzdGluXCI6XCIyOUFXR1BWNzEwN0IxWjFcIixcIkxnbE5tXCI6XCJYWVogY29tcGFueSBwdnQgbHRkXCIsXCJUcmRObVwiOlwiWFlaIEluZHVzdHJpZXNcIixcIlBvc1wiOlwiMzdcIixcIkFkZHIxXCI6XCI3dGggYmxvY2ssIGt1dmVtcHUgbGF5b3V0XCIsXCJBZGRyMlwiOlwia3V2ZW1wdSBsYXlvdXRcIixcIkxvY1wiOlwiR0FOREhJTkFHQVJcIixcIlBpblwiOjU2MDAwNCxcIlBoXCI6XCI5MDAwMDAwMDAwXCIsXCJFbVwiOlwiYWJjQGdtYWlsLmNvbVwiLFwiU3RjZFwiOlwiMjlcIn0sXCJEaXNwRHRsc1wiOntcIk5tXCI6XCJBQkMgY29tcGFueSBwdnQgbHRkXCIsXCJBZGRyMVwiOlwiN3RoIGJsb2NrLCBrdXZlbXB1IGxheW91dFwiLFwiQWRkcjJcIjpcImt1dmVtcHUgbGF5b3V0XCIsXCJMb2NcIjpcIkJhbmFnYWxvcmVcIixcIlBpblwiOjUxODM2MCxcIlN0Y2RcIjpcIjM3XCJ9LFwiU2hpcER0bHNcIjp7XCJHc3RpblwiOlwiMjlBV0dQVjcxMDdCMVoxXCIsXCJMZ2xObVwiOlwiQ0JFIGNvbXBhbnkgcHZ0IGx0ZFwiLFwiVHJkTm1cIjpcImt1dmVtcHUgbGF5b3V0XCIsXCJBZGRyMVwiOlwiN3RoIGJsb2NrLCBrdXZlbXB1IGxheW91dFwiLFwiQWRkcjJcIjpcImt1dmVtcHUgbGF5b3V0XCIsXCJMb2NcIjpcIkJhbmFnYWxvcmVcIixcIlBpblwiOjUxODM2MCxcIlN0Y2RcIjpcIjM3XCJ9LFwiSXRlbUxpc3RcIjpbe1wiSXRlbU5vXCI6MCxcIlNsTm9cIjpcIjFcIixcIklzU2VydmNcIjpcIk5cIixcIlByZERlc2NcIjpcIlJpY2VcIixcIkhzbkNkXCI6XCIxMDAxXCIsXCJCYXJjZGVcIjpcIjEyMzQ1NlwiLFwiUXR5XCI6MTAwLjM0NSxcIkZyZWVRdHlcIjoxMCxcIlVuaXRcIjpcIk5PU1wiLFwiVW5pdFByaWNlXCI6OTkuNTQ1LFwiVG90QW10XCI6OTk4OC44NCxcIkRpc2NvdW50XCI6MTAsXCJQcmVUYXhWYWxcIjoxLFwiQXNzQW10XCI6OTk3OC44NCxcIkdzdFJ0XCI6MTIsXCJJZ3N0QW10XCI6MTE5Ny40NixcIkNnc3RBbXRcIjowLFwiU2dzdEFtdFwiOjAsXCJDZXNSdFwiOjUsXCJDZXNBbXRcIjo0OTguOTQsXCJDZXNOb25BZHZsQW10XCI6MTAsXCJTdGF0ZUNlc1J0XCI6MTIsXCJTdGF0ZUNlc0FtdFwiOjExOTcuNDYsXCJTdGF0ZUNlc05vbkFkdmxBbXRcIjo1LFwiT3RoQ2hyZ1wiOjEwLFwiVG90SXRlbVZhbFwiOjEyODk3LjcsXCJPcmRMaW5lUmVmXCI6XCIzMjU2XCIsXCJPcmdDbnRyeVwiOlwiQUdcIixcIlByZFNsTm9cIjpcIjEyMzQ1XCIsXCJCY2hEdGxzXCI6e1wiTm1cIjpcIjEyMzQ1NlwiLFwiRXhwRHRcIjpcIjAxLzA4LzIwMjBcIixcIldyRHRcIjpcIjAxLzA5LzIwMjBcIn0sXCJBdHRyaWJEdGxzXCI6W3tcIk5tXCI6XCJSaWNlXCIsXCJWYWxcIjpcIjEwMDAwXCJ9XX1dLFwiVmFsRHRsc1wiOntcIkFzc1ZhbFwiOjk5NzguODQsXCJDZ3N0VmFsXCI6MCxcIlNnc3RWYWxcIjowLFwiSWdzdFZhbFwiOjExOTcuNDYsXCJDZXNWYWxcIjo1MDguOTQsXCJTdENlc1ZhbFwiOjEyMDIuNDYsXCJEaXNjb3VudFwiOjEwLFwiT3RoQ2hyZ1wiOjIwLFwiUm5kT2ZmQW10XCI6MC4zLFwiVG90SW52VmFsXCI6MTI5MDgsXCJUb3RJbnZWYWxGY1wiOjEyODk3Ljd9LFwiUGF5RHRsc1wiOntcIk5tXCI6XCJBQkNERVwiLFwiQWNjRGV0XCI6XCI1Njk3Mzg5NzEzMjEwXCIsXCJNb2RlXCI6XCJDYXNoXCIsXCJGaW5JbnNCclwiOlwiU0JJTjExMDAwXCIsXCJQYXlUZXJtXCI6XCIxMDBcIixcIlBheUluc3RyXCI6XCJHaWZ0XCIsXCJDclRyblwiOlwidGVzdFwiLFwiRGlyRHJcIjpcInRlc3RcIixcIkNyRGF5XCI6MTAwLFwiUGFpZEFtdFwiOjEwMDAwLFwiUGF5bXREdWVcIjo1MDAwfSxcIlJlZkR0bHNcIjp7XCJJbnZSbVwiOlwiVEVTVFwiLFwiRG9jUGVyZER0bHNcIjp7XCJJbnZTdER0XCI6XCIwMS8wOC8yMDIwXCIsXCJJbnZFbmREdFwiOlwiMDEvMDkvMjAyMFwifSxcIlByZWNEb2NEdGxzXCI6W3tcIkludk5vXCI6XCJET0MvMDAyXCIsXCJJbnZEdFwiOlwiMDEvMDgvMjAyMFwiLFwiT3RoUmVmTm9cIjpcIjEyMzQ1NlwifV0sXCJDb250ckR0bHNcIjpbe1wiUmVjQWR2UmVmclwiOlwiRE9DLzAwMlwiLFwiUmVjQWR2RHRcIjpcIjAxLzA4LzIwMjBcIixcIlRlbmRSZWZyXCI6XCJBYmMwMDFcIixcIkNvbnRyUmVmclwiOlwiQ28xMjNcIixcIkV4dFJlZnJcIjpcIllvNDU2XCIsXCJQcm9qUmVmclwiOlwiRG9jLTQ1NlwiLFwiUE9SZWZyXCI6XCJEb2MtNzg5XCIsXCJQT1JlZkR0XCI6XCIwMS8wOC8yMDIwXCJ9XX0sXCJBZGRsRG9jRHRsc1wiOlt7XCJVcmxcIjpcImh0dHBzOi8vZWludi1hcGlzYW5kYm94Lm5pYy5pblwiLFwiRG9jc1wiOlwiVGVzdCBEb2NcIixcIkluZm9cIjpcIkRvY3VtZW50IFRlc3RcIn1dLFwiRXhwRHRsc1wiOntcIlNoaXBCTm9cIjpcIkEtMjQ4XCIsXCJTaGlwQkR0XCI6XCIwMS8wOC8yMDIwXCIsXCJQb3J0XCI6XCJJTkFCRzFcIixcIlJlZkNsbVwiOlwiTlwiLFwiRm9yQ3VyXCI6XCJBRURcIixcIkNudENvZGVcIjpcIkFFXCJ9LFwiRXdiRHRsc1wiOntcIlRyYW5zSWRcIjpcIjEyQVdHUFY3MTA3QjFaMVwiLFwiVHJhbnNOYW1lXCI6XCJYWVogRVhQT1JUU1wiLFwiVHJhbnNNb2RlXCI6XCIxXCIsXCJEaXN0YW5jZVwiOjEwMCxcIlRyYW5zRG9jTm9cIjpcIkRPQzAxXCIsXCJUcmFuc0RvY0R0XCI6XCIwMS8wOC8yMDIwXCIsXCJWZWhOb1wiOlwia2ExMjM0NTZcIixcIlZlaFR5cGVcIjpcIlJcIn19IiwiaXNzIjoiTklDIn0.LNtgsBf5i0sryvbQ5DghqUufzHd-j8D4QJJjutu_CjPhyTWynmhzlSDNZk1fnw5kCTLseRkCT_AZ0S6vrwt3O_G6UH3ERZJnmXW0qizcM6dUmoSGmQF4Lqqd9XvdGOsT9c9_i-NQwiIJ1WVtmV2vkLUJ97eJcsjfjn6jO1Nh8tqqBIU_z7mtx78tqyaNQVfVLCmnMaaKoGQnNP4jtvpIiBR4mJn6MQXGCFksYqKdQEkInMWWCg93kBlsB3xgMHB9G1Bb8U_9NC7GXtlUdC3cv-SWEzu7ZRjDdg53j_zBt3EhQqg3ltyDv_94oF_LHz3gglIcAYfe0ljgyhbkNYyzgg",
  
  "SignedQRCode": "eyJhbGciOiJSUzI1NiIsImtpZCI6IkVEQzU3REUxMzU4QjMwMEJBOUY3OTM0MEE2Njk2ODMxRjNDODUwNDciLCJ0eXAiOiJKV1QiLCJ4NXQiOiI3Y1Y5NFRXTE1BdXA5NU5BcG1sb01mUElVRWMifQ.eyJkYXRhIjoie1wiU2VsbGVyR3N0aW5cIjpcIjAzQUFBQ1Y4NzIyRDFaT1wiLFwiQnV5ZXJHc3RpblwiOlwiMjlBV0dQVjcxMDdCMVoxXCIsXCJEb2NOb1wiOlwiTUFISS8xMFwiLFwiRG9jVHlwXCI6XCJJTlZcIixcIkRvY0R0XCI6XCIxMC8xMC8yMDIwXCIsXCJUb3RJbnZWYWxcIjoxMjkwOCxcIkl0ZW1DbnRcIjoxLFwiTWFpbkhzbkNvZGVcIjpcIjEwMDFcIixcIklyblwiOlwiMTk4NmRkMDgyZWQzN2ZkOWJlZjU0OThjYTY5MWU0M2VjNWZjYTYwZTE5YWUyODJkYjI1ZWUwNmJlY2Y1ZmJkN1wiLFwiSXJuRHRcIjpcIjIwMjEtMDItMjMgMTc6NDc6MDFcIn0iLCJpc3MiOiJOSUMifQ.dl1LKzKKIKtyspwE282-sVPAlBUTSzBB3nh_MeKAxdI6d9yHPVxhsAlcL0khJw4bWdTLY-C65BQw6e8rMXl0rplnSvs-aMm8qTZasgg_ZZuhFnjQLmsf9yLQZNcXiLn62CF132LGxHs5wy5R-mVIC_f6A0FQTJekJTT1RfXAgWwovGTKbIwbvjs7ZxGbc6obo-UJ-DXsqdqRdtEVNNKyI4d1jquB_4cXf4xUcfqRh_NBOgAL7idnustB3hZC-xTboeyKhhHMeQut5knb_qdt0TBASiCqRgek7r3cknHWzp7tOvmuz5siJxJ2XCdy6ANr3OVTC8YLs7CvITpdRH0RTw",
  },
  "status_cd": "1",
  "status_desc": "GSTR request succeeds"
}`

**It encode data as Date Format**

Please Suggest What to Do

**Comment by Irwin1985** [comment]
Hi, thanks for the feedback, I'll be testing using your data.

**Comment by Irwin1985** [comment]
Hi RightOpen, I noticed your json has a sintax error. There's a comma left after SignedQRCode value. Copy your data in https://jsoneditoronline.org/ for json validation.

**Comment by RightOpen** [comment]
Thanx

Thanks & Regards

Ravinder Kumar
+91 98144 61955
[RIGHT_LOGO]
