### ISSUE TITLE
Tokenizer Error

### ISSUE THREAD

**Issue by RightOpen** [Irwin1985/JSONFox#11]
![token](https://user-images.githubusercontent.com/32669003/108988269-46473b00-76ba-11eb-9122-6f4814cdcbdf.png)

**Comment by Irwin1985** [comment]
Are you calling the `parse `method from **JsonFox.app**? or hiting the **parser.prg** directly? if it's so remember calling **main.prg** first.

**Comment by RightOpen** [comment]
Hi
I am calling the parse method from JsonFox.app

Thanks & Regards

Ravinder Kumar
+91 98144 61955
[RIGHT_LOGO]

**Comment by Irwin1985** [comment]
Can you provide some code snippet of the example?

**Comment by RightOpen** [comment]
Frist Step

Response I receive from API Call

Response String
{
  "data": {
    "UserName": "vishal",
    "TokenExpiry": "2021-02-24 16:55:00",
    "Sek": "BE3vF24ZHRUWAhhA6Bx2WGGGQNSbMHZsOqEw9gOCZ5iaYjPvWAaSEc4Kw4bYOKO3",
    "ClientId": "AABCT29GSPS57O5",
    "AuthToken": "vOUtGbO6xQ5m81s9QXV3AHEkF"
  },
  "status_cd": "Sucess",
  "status_desc": "GSTR request succeeds",
  "header": {
    "username": "vishal",
    "password": "Vishal@1",
    "ip_address": "192.168.4.145",
    "client_id": "40ea7978-f1c5-4b71-800a-6672ebce807d",
    "client_secret": "e9b24bf8-3db1-4213-8666-f8948d674c41",
    "gstin": "03AAACV8722D1ZO",
    "gst_username": "vishal",
    "txn": "8a627a32a5514d579783194dccf154f9"
  }
}

Second Step
Parsing response

obj = _Screen.Json.Parse(Response)



Tokenize Error Occur


Thanks & Regards

Ravinder Kumar
+91 98144 61955
[RIGHT_LOGO]

**Comment by Irwin1985** [comment]
![image](https://user-images.githubusercontent.com/8443227/108992716-e93b8d00-7699-11eb-8de1-b4b254d70e13.png)
Try update the repo again bacause I did some changes lastnight.

**Comment by RightOpen** [comment]
Thanx for your concern.

I really appreciate your efforts for making thing happens within VFP.




Thanks & Regards

Ravinder Kumar
+91 98144 61955
[RIGHT_LOGO]

**Comment by RightOpen** [comment]
I have downloaded the new Files

Here is My Code


Do LocFile("JSONFox", "app")

TEXT TO jsondata NOSHOW
{
  "data": {
    "UserName": "vishal",
    "TokenExpiry": "2021-02-24 16:55:00",
    "Sek": "BE3vF24ZHRUWAhhA6Bx2WGGGQNSbMHZsOqEw9gOCZ5iaYjPvWAaSEc4Kw4bYOKO3",
    "ClientId": "AABCT29GSPS57O5",
    "AuthToken": "vOUtGbO6xQ5m81s9QXV3AHEkF"
  },
  "status_cd": "Sucess",
  "status_desc": "GSTR request succeeds",
  "header": {
    "username": "vishal",
    "password": "Vishal@1",
    "ip_address": "192.168.4.145",
    "client_id": "40ea7978-f1c5-4b71-800a-6672ebce807d",
    "client_secret": "e9b24bf8-3db1-4213-8666-f8948d674c41",
    "gstin": "03AAACV8722D1ZO",
    "gst_username": "vishal",
    "txn": "8a627a32a5514d579783194dccf154f9"
  }
}
ENDTEXT

_SCREEN.Json.parse(jsondata)





[cid:image002.png@01D70ACF.5F181200]
Thanks & Regards

Ravinder Kumar
+91 98144 61955
[RIGHT_LOGO]


From: Team ROSPL
Sent: 24 February 2021 16:48
To: 'Irwin1985/JSONFox' <reply@reply.github.com>; Irwin1985/JSONFox <JSONFox@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [Irwin1985/JSONFox] Tokenizer Error (#11)

Thanx for your concern.

I really appreciate your efforts for making thing happens within VFP.




Thanks & Regards

Ravinder Kumar
+91 98144 61955
[RIGHT_LOGO]
