### ISSUE TITLE
Jsonutils.CheckString not recognising some valid dates 

### ISSUE THREAD

**Issue by waltercsl** [Irwin1985/JSONFox#14]
Bug(s)  in CheckString  with datetimes, in my opinion..

jsonutils.CheckString( "2021-01-21T09:30:02" ) returns string .. but it is *Clearly* an ISO 8601-compliant date.
Nor does it identify  "2007-04-05T14:30"  which is the very example Wikipedia gives for this kind of date?

Also  "2019-08-21 16:25:34"  - identified correctly as a date/time  but  "2021-01-21 09:30:02"  is not.  Because it doesn't like leading zero (except at the midnight hour, 00:30:02  is )

The problem is of course primarily with regex patterns - in the ISO8601 it is requiring a time zone suffix, and in the second case it is not correctly detecting the two-digit hours.
I think a better ISO8601 pattern would be :
"^(\d{4})-(\d{2})-(\d{2})T(\d{2})\:(\d{2})(\:(\d{2}))?(Z|[+-](\d{2})\:(\d{2}))?$"

This allows optional seconds and the timezone can be omitted, or Z  (for UTC) or +hh:mm as was permitted before.

However, FormatDate( "2021-01-21T09:30:02+13:00" )  happens to fail anyway <g>  and as it is not doing timezone conversion, I can't find the enthusiasm for this format. 

So patch jsonutils.prg so that
```
datetime_pattern = "^\d\d\d\d-(0?[1-9]|1[0-2])-(0?[1-9]|[12][0-9]|3[01]) (00|0?[0-9]|1[0-9]|2[0-3]):([0-9]|[0-5][0-9]):([0-9]|[0-5][0-9])$"
iso_8601_pattern = "^(\d{4})-(\d{2})-(\d{2})T(\d{2})\:(\d{2})\:(\d{2})?(Z|[+-](\d{2})\:(\d{2}))?$"
```

I also suggest including this snippet at the front of FOrmatDate
```
if 'T' $ m.tcDate
	return ctot('^'+m.tcDate)
endif
```
This tactic works for both Javascript and ISO8601 dates (with the exception of +hh:mm timezone) without ever erroring on invalid input.  And it's a lot simpler than mucking with set date format.

Other comment, actually separate issue but so it is recorded somewhere.
This is bad enough of course, but also caused JsonToCursor() to crash on a 700-row data set; because it identified the data type of this column as "datetime null"   and then died 200-odd rows in with a wait window "Data Time Mismatch"

This also is a problem, sorry but ...
 catch
     wait window  loExc.message
endtry

... is not acceptable in production code.  It needs to set _screen.Json.lError = LastErrorText  , including ideally a row number (probably the only context you can get)  and bail out.

FWIW my tests of the above
do main.prg
clear
* These all 'succeed'
T( "2021-01-21 0:30:02" )
T( "2021-01-21 00:30:02" )
T( "2021-01-21 9:30:02" )
T( "2021-01-21 09:30:02" )
T( "2021-01-21T09:30:02" )
T( "2021-01-21T09:30:02Z" )
* These two still fail
T( "2021-01-21T09:30:02+13:00" )	&& Claims Pass but actually fails
T( "2021-01-21T09:30:02+1300" )	&& expecting fail anyway
function T( cInput )
	local lvResult
	lvResult = _screen.jsonutils.CheckString( m.cInput )
	if vartype( m.lvResult) = 'T'
		? 'Pass ' + padr(m.cInput,25) + ' [T] ' + transform(m.lvResult )
	else
		? 'FAIL ' + padr(m.cInput,25) + ' ['+vartype(m.lvResult)+'] ' + transform(m.lvResult)
	endif
endfunc

**Comment by Irwin1985** [comment]
Thanks for the feedback, I've implemented your suggested changes in the RegEx pattern and remove the wait window command from the JsonToCursor() method. I throw an error instead in order to be catched by the JSONClass and show the info to the user (see lShowErrors).
