### ISSUE TITLE
Ejemplo 3 del README.md

### ISSUE THREAD

**Issue by omsuarez** [Irwin1985/JSONFox#15]
Hola Irwin. 
El ejemplo 3 del README.nd (No es el mismo ejemplo de otra pregunta) que tiene las siguientes lineas, da como resultado .T. (true), no el json.

* Sample 3: Stringify Example

cJson = '{"age":45,"birthdate":"1985-11-15","created":"2020-07-28 09:29:41 PM","fullname":"Jhon Doe","gender":"Male","married":true,"soports":["running","swiming","basket-ball"]}'

?_Screen.Json.Stringify(cJson)

Saludos

**Comment by Irwin1985** [comment]
Hola omsuarez gracias por el feedbak, acabo de hacer la prueba y arroja un error, fue mi error por haber refactorizado la función stringify() sin hacer los tests para los casos boolean. Ya he subido la revisión y compilado JSONFox.app intenta probar y me dejas saber si funciona correctamente. 

Saludos!

**Comment by omsuarez** [comment]
Hola Irwin, muchas gracias por tu respuesta. El problema está solucionado con el cambio.
Puedes cerrar el caso.
Saludos Oscar.
