### ISSUE TITLE
Parser error with empty array and empty object

### ISSUE THREAD

**Issue by waltercsl** [Irwin1985/JSONFox#16]
Verified with 6.4  (pulled 2021-03-25 01:40 UTC). 
This is valid JSON as verified using https://jsonlint.com/ :

    do jsonfox.app
    x= _screen.json.Parse( '[]' )

**Result**  " Parser Error: Unknown token value: ']' "
**Expected**  object with one element, an array  such that  `x._[1 ] == 0`  and `alen(x._) == 1` as with example z below.

For comparison:
`y = _screen.json.Parse( '[ 4 ]' )`  returns an array with one numeric element ie y._[1] == 4
`z = _screen.json.parse('{"test_empty_array":[]}')` returns object with one propety z.test_empty_array[1] ==0

A second problem, rather worse error message: 

    _screen.json.parse('{}')

... results in "Operator/operand type mismatch."   

Because I'm being bitten by the empty array problem right now, I'll see if I can come up with a patch.

**Comment by waltercsl** [comment]
I've got a patch for the [] problem. ..  I'll attached.  Incidentally I think empty arrays _should_ be represented with _[1] = .null. - but you've got a precedent now so I'll make sure  it is _[1] = 0.  

The {}  problem is more insidious. All your token types are numeric except for T_NONE which .. well  I suggest `#define T_NONE 0`  and add `#define T_NOCHAR chr(4)`  because frankly that 'ÿ' is a desperate hack. chr(4) is the ASCII end-of-transmission. I'm looking into what the ramifications are.

**Comment by waltercsl** [comment]
Here's a patch for the empty array problem - [] (I'm not creating a pull request because it is simple enough, I'm not 100% sure I want the admin... and you might like the discussion) Two changes in parser.prg
First fixes [0] rather than [.null.]  for empty VFP array:
```
+++ b/src/parser.prg
@@ -48,18 +48,21 @@ define class Parser as custom
 		case this.cur_token.type == T_LBRACKET
 			local MyArray, nIndex
 			MyArray = createobject("Empty")
-			=addproperty(MyArray, '_[1]', .null.)
+			=addproperty(MyArray, '_[1]', 0) && for symmetry with This.array()
 			this.eat(T_LBRACKET)
```
Second fixes the failure to parse []
```
-			MyArray._[1] = this.value()
-			if this.cur_token.type != T_RBRACKET
-				do while this.cur_token.type = T_COMMA
-					this.eat(T_COMMA)
-					nIndex = nIndex + 1
-					dimension MyArray._(nIndex)
-					MyArray._[nIndex] = this.value()
-				enddo
+			* Check for empty array [ _whitespace_only_ ]
+			if this.cur_token.type != T_RBRACKET && non-empty array
+				MyArray._[1] = this.value()
+				if this.cur_token.type != T_RBRACKET
+					do while this.cur_token.type = T_COMMA
+						this.eat(T_COMMA)
+						nIndex = nIndex + 1
+						dimension MyArray._(nIndex)
+						MyArray._[nIndex] = this.value()
+					enddo
+				endif
 			endif
```

**Comment by waltercsl** [comment]
Fixing the empty object {} problem is a bit more insidious, because I found a bug I wasn't looking for.  Strategy - T_NONE is numeric like all the others (solves the operator/operand mismatch),  and a new symbol `T_EOT`  which you could leave as 'ÿ' if you like but I'm slightlyy more comfortable with a non-printable , hence `chr(4)`
This means in jsonfox.h:
```
-#Define T_NONE	'ÿ'
+#Define T_NONE	0
 #Define T_LBRACE	1
 #Define T_RBRACE	2
 #Define T_LBRACKET	3
@@ -21,4 +21,5 @@
 #Define CR	Chr(13)
 #Define LF	Chr(10)
 #Define CRLF	CR + LF
-#Define T_TAB	Chr(9)
+#Define T_TAB	Chr(9)
+#Define T_EOT	chr(4)
```
Then in tokenizer.prg just about every reference to T_NONE is changed to T_EOT ; except the one that creates the token object  ie `this.newToken(T_NONE, T_NONE)`  changes to `this.newToken(T_NONE, T_EOT)`

Finally though,  in parser.prg  object() method there is this snippet which I think must be wrong:
```
		this.eat(T_LBRACE)
-		if this.peek_token.type != T_RBRACE
+		if this.cur_token.type != T_RBRACE
 ...(etc)....          
		endif
		this.eat(T_RBRACE, "Expect '}' after JSON body.")
```
I can see why this might work most of the time, but it surely should be looking at the next token ie `if this.cur_token.type != T_RBRACE`
I'll attach the patch once I've run through some more tests.

**Comment by waltercsl** [comment]
[empty_json_patch.txt](https://github.com/Irwin1985/JSONFox/files/6201812/empty_json_patch.txt)
I don't have a comprehensive test suite,  but no problems found yet.

**Comment by Irwin1985** [comment]
Hi Walter, thanks for the feedback!
You're right, the empty array bug was in evidence in the code because the `MyArray._[1] = this.value() `was out of the `if this.cur_token.type != T_RBRACKET` control.

The empty object was a little verbose to fix due CONSTANT type mismatch _(thanks for noting it)_ but I finally did the changes and realize another bug along the way: in the object function I was checking for the next token type using `peek_token` property instead of _cur_token_

Hope not breaking anything else :)
