### ISSUE TITLE
ArrayToXML - Alias not found

### ISSUE THREAD

**Issue by omsuarez** [Irwin1985/JSONFox#17]
Hola Irwin.
Del video "COMO CONSUMIR UN API REST CON VISUAL FOXPRO   LIBRERIA VFPRESTCLIENT", copié el ejemplo, leyendo la tabla categoria, y al tratar de correr el ejemplo obtengo el siguiente memsaje en una pequeña ventana:
        ErrorNo : 13
        Message: Alias not found
        LineNo: 151
        Procedure: arraytoxml

El código usado es el siguiente (lo recibido se muestra como categoria/json):

clear
loRest = NEWOBJECT("rest", "D:\Documentos\VFP\VFPRestClient\vfprestclient.prg")
loRest.AddRequest(loRest.GET,"http://localhost/api/categoria/readOne.php?id=3")
LoRest.Send
?loRest.response

Do LocFile("D:\Documentos\VFP\JSONFox\JSONFox", "app")
obj=_Screen.Json.decode(loRest.response)
cXML = _Screen.Json.ArrayToXML(obj.data)

?cXML

Saludos, Oscar

**Comment by Irwin1985** [comment]
Vale, aquí si que hubo un bug en la función ArrayToXML(). Ya la he modificado para que acepte tanto objetos json como strings. En tu caso estás enviando el objeto data pero Fox solo te pasará el primer elemento de ese array por lo que tendrás que hacer una copia antes y enviar esa copia como referencia:

```
ACOPY(obj.data, aCopia)
cXML = _Screen.Json.ArrayToXML(@aCopia)
```

Actualiza JSONFox.app y con eso debe funcionar. Recuerda pasar la copia de los arrays con '@'
