### ISSUE TITLE
Problemas con STRINGIFY

### ISSUE THREAD

**Issue by omsuarez** [Irwin1985/JSONFox#19]
Hola Irwin:
En el siguiente ejemplo, usando STRINGIFY:
1.El archivo usado tiene un json con la siguiente estructura: code, data, message, status. Data es un arreglo de estructuras json.  (Al final el contenido de .txt).
2.Se carga (LOADFILE) un json desde un txt y se obtiene un objeto json (oJson1).
3.Se obtine un string usando STRINGFIY usando el objeto json (cJson1).
4.Se ontiene un string usando STRINGIFY usando del objeto json, la propiedad data (cJson1a).

El string obtenido del paso 3 (cJson1), contiene todo el json de .txt
El String obtenido del paso 4 (cJson1a), contiene **solo la primera** estructura del arreglo de estructuras en data.

El programa de prueba es:

clear
Do LocFile("D:\Documentos\VFP\JSONFox\JSONFox", "app")
cd (JUSTPATH(SYS(16)))

SET STEP ON

oJson1=_Screen.Json.LoadFile("jsonTst.txt")
cJson1=_Screen.Json.Stringify(oJson1)
cJson1a=_Screen.Json.Stringify(oJson1.data)
?cJson1
?"======================"
?cJson1a
[jsonTst.txt](https://github.com/Irwin1985/JSONFox/files/6253292/jsonTst.txt)

El contenido del archivo txt (jsonTst.txt):

{"status":"success","data":[{"id":2,"codigo":"WEB","descripcion":"Productos 
[jsonTst.txt](https://github.com/Irwin1985/JSONFox/files/6253293/jsonTst.txt)
WEB","created_at":"2021-03-07 07:58:31","modified_at":"2021-03-07 07:58:31"},{"id":3,"codigo":"Android","descripcion":"Productos Android","created_at":"2021-03-07 07:59:15","modified_at":"2021-03-07 07:59:15"},{"id":4,"codigo":"iPhone","descripcion":"Productos iPhone","created_at":"2021-03-08 11:24:50","modified_at":"2021-03-08 11:24:50"},{"id":7,"codigo":"Apple","descripcion":"Productos Mac","created_at":"2021-03-08 11:27:37","modified_at":"2021-03-08 11:27:37"},{"id":9,"codigo":"W10","descripcion":"Productos Windows 10","created_at":"2021-03-08 11:37:48","modified_at":"2021-03-08 11:37:48"},{"id":14,"codigo":"W7","descripcion":"Productos Window 7","created_at":"2021-03-09 05:03:57","modified_at":"2021-03-09 05:06:23"}],"code":200,"message":"categorias consultadas"}

Saludos Oscar

**Comment by Irwin1985** [comment]
Hola Oscar,

El problema está en el pase de arrays como parámetros. Fox no pasa el array sino su primer elemento. Para solucionarlo primero tienes que hacer una copia del array y pasar la copia a la función Stringify():

```
ACOPY(oJson1.data, aCategorias)
_Screen.Json.Stringify(aCategorias)

```

Con eso debe funcionar!
