### ISSUE TITLE
Ejecutando el ejemplo que está en el ReadMe

### ISSUE THREAD

**Issue by jhernancanom** [Irwin1985/JSONFox#2]
Hola, Irwin.
Estoy ejecutando el ejemplo que tienes en el ReadMe, pero me aparecen errores. 
Los dos primeros que aclaran lo que pasa; los adjunto en las sgtes dos imágenes.

Al ver que el campo debiera llamarse data (sin el guión subrayado), en el ejemplo creé una línea corrigiendo (supuestamente quitando tal guión), pero entonces --de todas formas-- la sgte línea (la que ejecuta ArrayToXML) dice que el tipo es inválido.

De hecho si suspendo y ejecuto desde la línea de comandos **? obj.data(1).name**, me aparece **Irwin1985**, correctamente considero yo.

¿Me indicas qué hacer?
Gracias.

![image](https://user-images.githubusercontent.com/5818845/103395175-d3c34000-4afa-11eb-92c8-6d2bc9b030e4.png)

![image](https://user-images.githubusercontent.com/5818845/103395170-ca39d800-4afa-11eb-88af-cd2b82473ad5.png)

**Comment by Irwin1985** [comment]
Hola Hernán, muchas gracias por probar la librería y darte cuenta que el ejemplo del [README.md](https://github.com/Irwin1985/JSONFox/blob/master/README.md) tiene fallas. Lo he actualizado con la nueva forma de convertir arrays a cursores y viceversa. Prueba y dime si consigues alguna falla. 

Saludos!
