### ISSUE TITLE
Pregunta sobre XMLTOJSON

### ISSUE THREAD

**Issue by omsuarez** [Irwin1985/JSONFox#20]
Hola Irwin.
Cuando uso XMLTOJSON, el json generado tiene corchetes al comienzo y al final, como si fuera un array. Si revisas tu video "COMO CONSUMIR UN API REST CON VISUAL FOXPRO   CRUD CATEGORIAS 45" mas o menos en el minuto 18:45, a la izquierda se muestra el procedimiento CREATE en VFP y a la derecha la ventana de "watch". En esta ultima muestra que el contenido de la variable cJson no tiene esos corchetes. El programa create.php tal como esta, falla al no esperar un arreglo como grupo inicial. Que debo hacer, modificar el programa en PHP? o eliminar esos corchetes? Temporalmente esto último es lo que estoy haciendo.

Saludos Oscar

**Comment by Irwin1985** [comment]
Hola Oscar, en cualquiera de los dos sitios puedes adaptar el cambio sin problemas. Si ya te funciona con la eliminación de los corchetes entonces déjalo así y trabaja bajo esa modalidad.

saludos!
