### ISSUE TITLE
Speed issue with parse

### ISSUE THREAD

**Issue by rromero1956** [Irwin1985/JSONFox#21]
Hi
the app works and for most cases (small physical size) it work well
I was working with a Json file that has embedded a PDF file (size of the file is approx. 500K)
Under this condition it was to slow to handle this type a message.

The problem is how you handle the string in the string function inside the Tokenizer
I am appending the modified version of this function
It need to be tested more but so far it is 10 times or more faster than the original version

	function string
	lexeme = ''
	mOffset = 0
	 mNumDoubQouts = occurs('"', left(this.source, this.pos-1))
	mDone = .F.
	do while !mDone
          myStrTmp = strextract(this.source, '"', '"', mNumDoubQouts+1)
          if right(myStrTmp,1)="\"
            lexeme = lexeme + left(myStrTmp,len(myStrTmp)-1) + '"'
            mOffset = mOffset + 1
            mNumDoubQouts = mNumDoubQouts + 1
          else
            lexeme = lexeme + myStrTmp
            mDone = .T.
          endif
	enddo
        this.pos = this.pos + len(lexeme) + mOffset + 1
        * handle scape chars
         lexeme = strtran(lexeme,"\\","\")
         lexeme = strtran(lexeme,"\n",LF)
         lexeme = strtran(lexeme,"\r",CR)
         lexeme = strtran(lexeme,"\t",T_TAB)
         * maybe something here for unicodes
        this.advance()
		
        * lcPeek = ''
        * this.advance() && advance the first '"'
        * do while this.current_char != T_NONE
        *   if this.current_char = '\'
        *     lcPeek = this.peek()
        *     do case
        *     case lcPeek = '\'
        *       this.advance()
        *       lexeme = lexeme + '\'
        *     case lcPeek = 'n'
        *       this.advance()
        *       lexeme = lexeme + LF
        *     case lcPeek = 'r'
        *       this.advance()
        *       lexeme = lexeme + CR
        *     case lcPeek = 't'
        *       this.advance()
        *       lexeme = lexeme + T_TAB
        *     case lcPeek = '"' and this.pos + 1 < len(this.source)
        *       this.advance()
        *       lexeme = lexeme + '"'
        *     case lcPeek = 'u'
        *       this.advance()
        *       lexeme = lexeme + this.getUnicode()
        *     otherwise
        *       lexeme = lexeme + '\'
        *     endcase
        *   else
        *     if this.current_char = '"'
        *       this.advance() && eat the last '"'
        *       exit
        *     else
        *       lexeme = lexeme + this.current_char
        *     endif
        *   endif
        *   this.advance()
        * enddo
	return this.newToken(T_STRING, lexeme)
	endfunc

Sorry about the indentation, I try to fix it but it was to much

Here are some of the test files I was using
- xHisStm (it has a pdf file embedded)
- sJsonSpecial (has some special characters)

[xHistStm.txt](https://github.com/Irwin1985/JSONFox/files/6288959/xHistStm.txt)
[xJsonSpecial.txt](https://github.com/Irwin1985/JSONFox/files/6288960/xJsonSpecial.txt)

**Comment by Irwin1985** [comment]
That's a clever solution, let me know if it passes all tests scenarios. Congrats!
