### ISSUE TITLE
guardar archivo .json

### ISSUE THREAD

**Issue by benrojas01** [Irwin1985/JSONFox#22]
Hola Irwin

me puedes por favor explicar como convierto un cursor en un archivo .json

gracias

**Comment by Irwin1985** [comment]
```
Do JSONFox.app
Use c:\mi\ruta\al\dbf alias miTabla
?_screen.json.cursortojson('miTabla')
```
Eso convierte todo tu cursor en formato JSON. Si quieres solo la fila actual entonces pasa .T. como segundo parámetro.

**Comment by benrojas01** [comment]
Gracias Irwin,

eso lo he logrado sin problemas, ahora quiero guardar esto como un
documento para consultarlo luego, es posible ?
digamos algo como copy to micursorjson  type json

saludos,

**Comment by Irwin1985** [comment]
Guardalo con `STRTOFILE(lcContenidoDelJSON, 'c:\ruta\del\fichero.json')` y luego lo recuperas con obj = `_SCREEN.json.parse(FILETOSTR('c:\ruta\del\fichero.json'))`

**Comment by benrojas01** [comment]
muchas gracias Irwin
