### ISSUE TITLE
Cuando el encode devuelve un solo registro.

### ISSUE THREAD

**Issue by Jaketon** [Irwin1985/JSONFox#27]
Buenas en el caso de que se haga un GET y se genere esta respuesta por el Ws (Json) donde clientes tenga más de una entrada me lo encierra entre [ ] (corchetes) en la función php: print json_encode($datos); del Ws

{
    "estado": 1,
    "clientes": [
        {
            "id": "00000000000000000028",
            "cif": "cif1",
            "razon": "Nombre 1",
            "id_procesador": "BFEBFBFF000306C3",
            "licencia": "C0000",
            "actualizaciones": "1",
            "fecha_creacion": "2019-04-29 17:11:24"
        },
        {
            "id": "00000000000000000033",
            "cif": "cif2",
            "razon": "Nombre 2",
            "id_procesador": "BFEBFBFF000406C4",
            "licencia": "C0293",
            "actualizaciones": "1",
            "fecha_creacion": "2019-05-16 18:51:26"
        },
        ........................ etc..................
    ]
}

Pero si el Ws solo devuelve un registro, obtengo de la misma funcion print json_encode($datos); donde clientes ya no esta entre [ ] (corchetes)

{
    "estado": "1",
    "clientes": {
        "id": "00000000000000000028",
        "cif": "cif1",
        "razon": "Cliente1",
        "id_procesador": "BFEBFBFF000306C3",
        "licencia": "C0000",
        "actualizaciones": "1",
        "fecha_creacion": "2019-04-29 17:11:24"
    }
}

Esto provoca que la funcion de la clase ArrayToXML de un error pq no encuentra los [ (corchetes) del arreglo, pese a que la funcion php json_encode no se los coloca.

¿Donde puede estár el problema?

**Comment by Irwin1985** [comment]
El _"problema"_ lo tiene el web service porque debería de devolverte siempre un array sin importar la cantidad de filas que tenga. Si has programado el servicio tu mismo entonces ya sabes donde arreglarlo, sino entonces puedes resolver de esta manera:

Suponiendo que **lcJSONResponse** es la respuesta del servicio, entonces:

```
loData = _screen.json.parse(lcJSONResponse)

If Type('loData.Clientes', 1) == 'A' && Es un array
   && tratarlo como array
Else && Es tipo 'U' con lo cual no es un array sino otro tipo de dato
   && sacar los valores a mano (loData.Clientes.Razon, etc)
Endif
```

Suerte!

**Comment by Jaketon** [comment]
Correcto el problema está en Ws.

**Comment by Jaketon** [comment]
Por otro lado he puesto este ejemplo tal como aparece y en la línea (_Screen.Json.JSONToCursor(lcJsonArray, "qEmployees")) me da un error 1098, field name is a duplicate or invalid. linea 219 procedure createcursor. Saludos.

 * Sample 2: JSONArray to Cursor
 Text To lcStr NoShow
	 {
	  "status": "success",
	  "data": [
	    {
	      "id": 2,
	      "email": "rodriguez.irwin@gmail.com",
	      "name": "Irwin1985",
	      "lastName": "Rodriguez",
	      "sex": "1",
	      "salary": 2278.45,
	      "profesion_id": 1,
	      "birthDate": "1985-11-15",
	      "createdAt": "2019-03-31",
	      "single": true
	    },
      {
          "id": 3,
          "email": "oscaraguero85@gmail.com",
          "name": "oscar",
          "lastName": "aguero",
          "sex": "1",
          "salary": 1500.45,
          "profesion_id": 1,
          "birthDate": "1985-06-18",
          "createdAt": "2021-10-11",
          "single": true
      }      
	  ],
	  "code": 200,
	  "message": "success"
	}
ENDTEXT

obj = _Screen.Json.Parse(lcStr)

* Make a copy of the internal array from obj.data
Acopy(obj.data, aEmployeeList)

* Now pass the aEmployeeList by reference with '@'
lcJsonArray = _Screen.Json.Encode(@aEmployeeList)

* Convert the JSONArray into VFP CURSOR **(this is cool)**
_Screen.Json.JSONToCursor(lcJsonArray, "qEmployees")

* Modify some fields
Select qEmployees

**Comment by Jaketon** [comment]
Para no depender del entorno de SET EXACT todos los ASCAN de la clase debería de ser con estos parámetros:
ascan(this.aTableStruct, tcFieldName,-1,-1,0,4). Quitando los perjuicios que puede causar tener el set exact en off para esta función.

**Comment by Irwin1985** [comment]
Que gran ayuda me acabas de brindar, no sabía que tenia un bug dormido con el SET EXACT. Ya he actualizado la librería. Muchas gracias por detectar el error y de paso ofrecerme la solución.
