### ISSUE TITLE
Abriendo el Proyecto

### ISSUE THREAD

**Issue by jhernancanom** [Irwin1985/JSONFox#3]
Hola, Irwin.
Estoy abriendo el proyecto, pero aparece un error.
Dice que falta un formulario.
Si le doy ignorar, continúa con normalidad.
Si ejecuto el **main**, no hace nada. Considero que ese es el comportamiento normal para ejecutar el APP.

Considero que sólo tienes que eliminar el formulario JSON Viewer simplemente del proyecto, pues cuando ejecuto el ejemplo -- que sólo necesita el APP-- trabaja bien..

Gracias.

![image](https://user-images.githubusercontent.com/5818845/103395690-695fcf00-4afd-11eb-8dae-e8b72a90a686.png)

**Comment by Irwin1985** [comment]
Hola Hernán, gracias por notarlo. Ya mismo reviso el formulario y subo la corrección.

Saludos!

**Comment by eliager** [comment]
Hola Irwin,

Aun no veo el formulario con la corrección, 

Gracias por compartir estas librerias,

**Comment by Irwin1985** [comment]
Hola Eliager, tienes razón. Tenia la extensión SCX ignorada y por eso no me di cuenta que no subía el formulario. Ya puedes descargar todo el proyecto porque lo he subido nuevamente.

https://github.com/Irwin1985/JSONFox/blob/master/src/frmjsonviewer.scx
