### ISSUE TITLE
Version 9.3 - Error parsing empty ARRAY

### ISSUE THREAD

**Issue by twoedges** [Irwin1985/JSONFox#36]
Hi,
trying to parse following JSON string

```
{
   "returncode":"ok",
   "messages":[]
}
```

library return this error

![image](https://user-images.githubusercontent.com/8215717/201359319-5d501f38-4fb7-407f-93fb-af67e525f691.png)

Of course string is a valid JSON ...

**Comment by Irwin1985** [comment]
Hi, thanks for the feedback. I'm working on it right now...

**Comment by Irwin1985** [comment]
wow this is really really weird! 

VFP doesn't allow us to create an array on empty objects with the following names:

```
loTest = CreateObject('Empty')
AddProperty(loTest, 'messages[1]', .null.) && RUNTIME ERROR
AddProperty(loTest, 'message[1]', .null.) && RUNTIME ERROR
AddProperty(loTest, 'update[1]', .null.) && RUNTIME ERROR
```

I think these are reserved keywords underlaying empty objects but I'm not pretty sure though, either way it ruined the parsing process :( now i dont know whether intercept and change those words or let the library consumer to deal with it. What a mess...

**Comment by twoedges** [comment]
Hi Irwin,
thanks for your great work but, after downloading version 9.5 error message remains :(

**Comment by Irwin1985** [comment]
Sorry, I can't check for every key because that would slow all the process. I can throw an error and then you catch it with `try/catch` instead of showing the `wait window` message.
