### ISSUE TITLE
Loop infinito con for y variable "i"

### ISSUE THREAD

**Issue by Terterola** [Irwin1985/JSONFox#39]
Hola Irvin!

Me acabo de enterar y estoy haciendo tests iniciales con JSONFox.

Hice un test simple con un loop "for" usando una variable llamada "i" como contador. Lo que pasó fue que la rutina entró en un loop infinito. 

Si cambio la variable a cualquier otro nombre, el loop funciona normalmente.

Envio una imagen con el código y las impresiones en loop hasta cancelar con ESC.

<img width="754" alt="loop_infinito" src="https://user-images.githubusercontent.com/6319010/210098321-b3eb95df-db26-4fe3-9a79-da44d6de8860.png">

Podría ser algo en la biblioteca, o algún error de mi parte?

Gracias!

**Comment by Irwin1985** [comment]
Hola @Terterola muchas gracias por el feedback y perdona el error, es mi culpa, olvidé declarar esa variable en varios loops que uso internamente. Ya puedes bajar la [revisión](https://github.com/Irwin1985/JSONFox/releases/tag/jsonfoxv9) y hacer las pruebas nuevamente.

Me dices si funciona para cerrar el issue.

Un saludo.

**Comment by Terterola** [comment]
No por eso, cómo decimos aquí en Brasil, "estamos juntos". Necesito modernizar mi aplicación VFP y su biblioteca puede ayudarnos mucho. Un momento y te vuelvo a llamar.

**Comment by Terterola** [comment]
Todo perfecto ahora. Este problema con las variables de VFP en conflicto es relativamente común...
Muchas gracias y un gran año nuevo. Ah, conozco Toledo, hermosa ciudad!
