### ISSUE TITLE
Preg1: Sobre Stringify y JsonStringify

### ISSUE THREAD

**Issue by jhernancanom** [Irwin1985/JSONFox#4]
Hola, Irwin.

Te consulto sobre el dos funciones que veo muy similares.

Me gustaría saber la diferencia entre .Stringify() y .JsonStringify()

.**Stringify**(tvNewVal As Variant)

.**JsonStringify**(cJsonStr [, cFlags])

Diferencias:
1. Veo que .Stringify() puede recibir (1) un objeto o (2) un texto en formato JSON; pero .JSONStringify() sólo puede recibir un texto en formato JSON.
2. Veo que .JSONStringify() puede recibir dos parámetros; pero .Stringify() sólo puede recibir uno.

Gracias.

**Comment by Irwin1985** [comment]
Hola Henan, revisando la documentación he visto que he dejado la función **JSONStringify** como parte de la interfaz pública de la API y no es verdad. Ya la he quitado porque realmente la que está expuesta es **Stringify()** que de hecho recibe 1 parámetro obligatorio y uno opcional. El obligatorio puede ser un texto json o bien un objeto Fox, internamente la función se apoya con **JSONStringify()** para deserializar objetos por lo tanto ésta solo funciona como helper.
