### ISSUE TITLE
local variable error on ObjectToJSON.AnyToJson()

### ISSUE THREAD

**Issue by DanielCarlos231** [Irwin1985/JSONFox#44]
You have a commented the array variable aCopy declaration of local, so it is causing to replecate its contents on the next array of the json object.
![image](https://github.com/Irwin1985/JSONFox/assets/89362488/dd8cfd6d-c989-4cd5-a5e9-0fb0421a3502)

I just uncommented this part and the code worked just fine.

You can use this json String to better undestand what I'm saying 
```
TEXT TO PRVSJSN001 NOSHOW TEXTMERGE
	{
	  "attributes": [
	    null
	  ],
	  "available": [
	    null
	  ],
	  "brand": "COCA COLA                          ",
	  "categories": [
	    {
	      "name": ""
	    },
	    {
	      "name": ">MERCEARIA LIQUIDA                                                                                                                                                                                      "
	    }
	  ],
	  "cest": "0301002",
	  "cost": 2.520000,
	  "description": "REFR COCA COLA LT 350ML                                                         ",
	  "dimension": {
	    "height": 0,
	    "length": 0,
	    "weight": 0,
	    "width": 0
	  },
	  "ean": "07894900010015",
	  "external": "0000001",
	  "handling_time": 0,
	  "link": "",
	  "manufacture_time": 0,
	  "model": "",
	  "name": "REFR COCA COLA LT 350ML            ",
	  "ncm": "22021000",
	  "photos": [null],
	  "price": 3.79,
	  "price_table": [null],
	  "quantity": 11017,
	  "short_description": "REFR COCA COLA LT 350ML  ",
	  "sku": "0000001",
	  "special_price": 0,
	  "stock_table": [],
	  "variations": [],
	  "warranty_message": "",
	  "warranty_time": 0
	}
ENDTEXT

prvojsndat = _Screen.Json.Parse(PRVSJSN001)

*SET STEP ON

&& the arrays after the categories[] array will have the same values of the categories[], and they should not 
_CLIPTEXT = _Screen.JSON.Stringify(prvojsndat)
```
I noticed you have also commented the local declaration of other arrays variables in the same AnyToJson function.
I don't know whether this is intentional or not, and I also don't know if it is causing any bugs... I just wanted to also report this, so if you want to ckeck that as well

**Comment by Irwin1985** [comment]
Thanks for reporting this issue Daniel, ACOPY() does not declare the array as LOCAL and keeps updating itself in every iteration. I just declared it as LOCAL and I believe that solved the issue.

Please update JSONFox.app v9.10 and let me know if everything works as expected.

**Comment by DanielCarlos231** [comment]
There one small detail that is causing another bug...

You have chage the aCopia[] to laLista[] on the " case vartype(tValue) = 'O'  ", but you still send the aCopia in the " lcJSONStr = lcJSONStr + this.AnyToJson(@aCopia)  "
![image](https://github.com/Irwin1985/JSONFox/assets/89362488/81ba711a-8b49-4241-9185-1c2aa4dcc56b)
 I changes the " lcJSONStr = lcJSONStr + this.AnyToJson(@aCopia)  " to " lcJSONStr = lcJSONStr + this.AnyToJson(@laLista)  " and this way it works

**Comment by Irwin1985** [comment]
oh I'm sorry, I didn't realise I left that error behind. Please update JSONFox.app v9.11 and try again.

PD: thatks for your kind words about JSONFox, I really appreciate it.

**Comment by DanielCarlos231** [comment]
This version worked just fine, Thanks 😁
