### ISSUE TITLE
scientific notation bug

### ISSUE THREAD

**Issue by DanielCarlos231** [Irwin1985/JSONFox#47]
I found a bug with scientific notation, i'm still trying to find a work arround

![image](https://github.com/Irwin1985/JSONFox/assets/89362488/2aa51ebe-ff7b-4920-907a-6e4cc1c5060c)

I just wanted to report the issue to let you know... if I find any solution before you do I'll post my solution here

**Comment by DanielCarlos231** [comment]
I've found a solution
![image](https://github.com/Irwin1985/JSONFox/assets/89362488/033c0011-af15-4942-8cd7-49823b74d24f)

I added the following code, to the Tokenizer class in the hidden function number()
```
&& Check if number is a Scientific Notation in Tokenizer.Number()
IF .peek() + .peekNext() == "e+" 
  .advance()
  .advance()
  do while isdigit(.peek())
	  .advance()
  enddo	
ENDIF
*****************************************************************
```
From what I could understand when a number was in scientific notation the number() function would stop on the "e" and would come back with only the part before the "e".
And the last part of the scientific notation would generate the errror on the json.

**Comment by Irwin1985** [comment]
Hi Daniel, that's a nice solution. I've added the fix and compiled the app. Thank you!

**Comment by DanielCarlos231** [comment]
Hi Irwin, I'm happy you liked my solution😁
