### ISSUE TITLE
Preg3: Sobre ejemplo 3 del ReadMe

### ISSUE THREAD

**Issue by jhernancanom** [Irwin1985/JSONFox#5]
Preg3: Sobre ejemplo 3 del ReadMe
----------------------------------------
Hola, Irwin.

Te consulto sobre el **ejemplo 3 del ReadMe** que se ve en la pantalla principal.

Lo veo confuso, y de hecho no funciona.

Me parece que no hay relación entre la clase que mencionas que nosotros tendríamos para hacer algo con tu clase.

Primero tenemos la clase oPerson.
Pero luego se habla del objeto oJohn, que no tiene relación con oPerson.
Incluso oJohn está basado en **JsonDecorator**.prg que no está en la descarga de tu clase.
Para que una instrucción como " ?oJhon.to_json() " me dé una respuesta como la mostrada, debiera usarse Stringify --que es lo que se muestra en el ejemplo4--.

Ahora si lo que quisiéramos es "to extend this person class", entonces debiera haber comandos (código) para agregar propiedades, y luego algo como .**ToJSON**() --que no se existe (en la doc actual, con un nombre similar) en tu clase--, pero que yo entiendo como .Stringify().

** oPerson
** ?_Screen.Json.Stringify(oPerson)

Se adjunta __Ejemplo_03-Ajustado.prg__ para mostrar un escenario probable para lo indicado.

```
* Sample 3: Decorate and print any class

* Now you can use JSONFox as a compiled App...
 Do LocFile("JSONFox", "app")

* Suppose you have a person class.
** ** oPerson = CreateObject("PersonClass")
oPerson = CreateObject("Empty")
Addproperty(oPerson,'fullname' , "")
Addproperty(oPerson,'age'      , "")
Addproperty(oPerson,'gender'   , "")
Addproperty(oPerson,'married'  , "")
Addproperty(oPerson,'created'  , "")
Addproperty(oPerson,'birthdate', "")
With oPerson
	.fullname = "Jhon Doe"
	.age = 45
	.gender = "Male"
	.married = .T.
	.birthdate = Date(1985, 11, 15)
	.created = Datetime()
EndWith

** ** * Now you need to extend this person class
** ** oJhon = NewObject("JSon", "JsonDecorator.prg")
** ** ?oJhon.to_json()
** ** {
** **   "age": 45,
** **   "birthdate": "1985-11-15",
** **   "created": "2020-07-28 09:29:41 PM",
** **   "fullname": "Jhon Doe",
** **   "gender": "Male",
** **   "married": true
** ** }

** 
Addproperty(oPerson,'profession', "Systems Analyst")
** 
?_Screen.Json.Stringify(oPerson)

**
```

**Comment by Irwin1985** [comment]
Ya no es necesario extender de _json_decorator.prg_ ya que fue antes de que existiera **Stringify().**
