### ISSUE TITLE
ejecutar jsonfox como prg

### ISSUE THREAD

**Issue by benrojas01** [Irwin1985/JSONFox#52]
Buenas tardes Irwin

quería preguntarte si es posible ejecutar jsonfox como un prg  ej do jsonfox.prg... , ya que entiendo que hay varios prg compilados en el app y requiero usarlo como un programa

quedo atento a comentarios, muchas gracias

cordial saludo,

**Comment by DanielCarlos231** [comment]
Bueno, la forma en que está construido se supone que debe usarse como una APLICACIÓN, pero si no quieres usarlo como una APLICACIÓN, puedes copiar todas las clases dentro de cada archivo PRG en solo un archivo PRG.
Luego debes ejecutar el código dentro del archivo PRG loader para que funcione, ya que deseas tener solo un PRG, asume que querrías crear una función llamada loader' dentro del archivo PRG en el que deseas mantener el código JSONFox.
Luego solo necesitas ejecutar 'SET PROCEDURE TO JSONFOX.PRG ADDI' y ejecutar la función loader'.
De esta manera, aún deberías poder acceder a JSONFox a través de '_screen.json'.

**Comment by DanielCarlos231** [comment]
Si colocas todo dentro de un archivo PRG, no sería necesario estes 'SET PROCEDURE'.
Y no olvides incluir todos los archivos '*.h' que están incluidos en las clases mediante '#INCLUDE'.
![image](https://github.com/Irwin1985/JSONFox/assets/89362488/229e8c49-25a3-4918-9598-f2ad0015687f)
