### ISSUE TITLE
¿Cómo leer este arreglo?

### ISSUE THREAD

**Issue by jhernancanom** [Irwin1985/JSONFox#54]
Hola, amigos.
¿Cómo puedo hacer para capturar a un objeto un JSON con la sgte esctructura...?
Nótese que inicia y termina con corchetes (paréntesis cuadrados).

```
[
    {
        "num_factura": "ABC12345",
        "fecha": "2024-02-23T00:00:00",
        "codigo": "123456789",
        "nombre": "ENRIQUE",
        "pagada": true,
        "valor": 123456789.00
   },
    {
        "num_factura": "ABC12346",
        "fecha": "2024-02-21T00:10:11",
        "codigo": "AT008",
        "nombre": "CONZALO",
        "pagada": false,
        "valor": 9876543.00
   }
]
```
Si ejecuto un simple 
```
M.oObj = _Screen.Json.Parse(M.cJson)
```
aparece un mensaje de error de "comando no reconocido" en TokenToStr.
![image](https://github.com/Irwin1985/JSONFox/assets/5818845/94f9acf1-c2fd-41c1-ba21-81be2d88f298)

**Comment by Irwin1985** [comment]
Parece que hay algo en el string del json que no es reconocido por JSONFox. El string lo estás enviando desde qué fuente de datos? HTTP, fichero de texto, etc? Te dejo una imagen con el ejemplo realizado en mi ordenador.
![image](https://github.com/Irwin1985/JSONFox/assets/8443227/72dce03d-80e6-47f2-85b7-557d86060ded)

**Comment by jca-ec** [comment]
Hola, Yo hace tiempo tuve ese problema:
En Visual FoxPro lo solucioné así:
_Screen.Json.Parse(StrExtract(_Screen.Json.CursorToJson('InfoRuc'),'[',']'))

**Comment by jhernancanom** [comment]
> Parece que hay algo en el string del json que no es reconocido por JSONFox. El string lo estás enviando desde qué fuente de datos? HTTP, fichero de texto, etc? Te dejo una imagen con el ejemplo realizado en mi ordenador. ![image](https://private-user-images.githubusercontent.com/8443227/307414662-72dce03d-80e6-47f2-85b7-557d86060ded.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3MTQyMjYsIm5iZiI6MTcwODcxMzkyNiwicGF0aCI6Ii84NDQzMjI3LzMwNzQxNDY2Mi03MmRjZTAzZC04MGU2LTQ3ZjItODViNy01NTdkODYwNjBkZWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjNUMTg0NTI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmIwNmJmOThlNzIyNDk4YTE5NGMxYjNjNzE1MjEyM2U2ZTk5ZGM0OTQ5YTI1MmI2YTQ4NjE2MGZlM2IyOGIxMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.VkOmGjTT2nJRGrbIjcBuKkQB5Wgg5JDhSjvJq_yPcp0)

**Comment by jhernancanom** [comment]
Correcto.
> Parece que hay algo en el string del json que no es reconocido por JSONFox. El string lo estás enviando desde qué fuente de datos? HTTP, fichero de texto, etc? Te dejo una imagen con el ejemplo realizado en mi ordenador. ![image](https://private-user-images.githubusercontent.com/8443227/307414662-72dce03d-80e6-47f2-85b7-557d86060ded.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3MTQyMjYsIm5iZiI6MTcwODcxMzkyNiwicGF0aCI6Ii84NDQzMjI3LzMwNzQxNDY2Mi03MmRjZTAzZC04MGU2LTQ3ZjItODViNy01NTdkODYwNjBkZWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjNUMTg0NTI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmIwNmJmOThlNzIyNDk4YTE5NGMxYjNjNzE1MjEyM2U2ZTk5ZGM0OTQ5YTI1MmI2YTQ4NjE2MGZlM2IyOGIxMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.VkOmGjTT2nJRGrbIjcBuKkQB5Wgg5JDhSjvJq_yPcp0)
