### ISSUE TITLE
Dificultad con un Json *grande*

### ISSUE THREAD

**Issue by jhernancanom** [Irwin1985/JSONFox#57]
Tengo un JSON simple, similar a lo sgte:
```
{
  "registro": 1,
  "nombre": "HERNAN",
  "codigo": "0123",
  "salario": 12345
}
```
Simple significa que no hay "objetos anidados".

En producción son más campos y los registros crecen.

Cuando el JSON que recibo del servicio web tiene por ejm 29 Kb (veintinueve kilobytes), JsonFox lo procesa normal, más o menos con:
```
M.oObj = _Screen.Json.Parse(FileToStr(M.lcOrg))`
```
Pero cuando el JSON tiene más de dos cientos kilobytes (245 Kb, por ejm), el proceso falla, obtengo un oObj nulo.

Cuando escudriño el sistema, veo que recibo el sgte error (ver imagen):

`Identificador **N** no esperado`

![image](https://github.com/Irwin1985/JSONFox/assets/5818845/7d2e6cbc-e4b4-4114-a613-c36261ba9a96)

Lo q se ve entre paréntesis en el mensaje de error (1:15786) lo agregué a la clase para ver dónde se produce en inconveniente; creo entender que se refiere al número de bytes donde va el scaneador de keywords. Si miro el Json, ésa cantidad me llega a mitad de uno de los campos del Json, el nombre de uno de los campos, pero es un campo de caracteres, no tiene valores inválidos, ni tildes, ni nada diferente a algo que que haya procesado en los registros anteriores, o con menos registros.

Pero evidentemente no sé dónde debo buscar.

Sólo se me ocurre que es por el tamaño del archivo, pero espero ayuda al respecto.

De todas formas tanto con 
.NetScannner = .f. aparece el mismo mensaje de error en la misma línea que con 
.NetScannner = .t. (confirmo que JSONFoxHelper.dll está junto a JsonFox.app, y ambos alcanzables por mi app).

**Comment by Irwin1985** [comment]
Hola @jhernancanom, lo que ves entre paréntesis es la línea y la columna donde está el caracter que ha causado el error. En este caso línea 1 y columna 15786. Puedes validar el contenido de tu JSON en algún sitio online como https://jsoneditoronline.org/ para ver si no presenta problemas? o si puedes compartirlo para hacer pruebas estaría genial.

PD: además de .NetScanner también puedes usar .JScriptScanner = .T. para que active el escáner de JScript que también va super rápido y es más ligero.

**Comment by sixtored** [comment]
Como lo convertis.? Con strconv..?

Atte.
Sixto

**Comment by jhernancanom** [comment]
Buenas tardes, amigos.

Correcto, Irwin: hice los ajustes que me recomendaste y mis conclusiones son los sgtes:

_0. Para poder desarrollar estos tests, debí hacer ajustes manuales a los programas fuente de JSONFox, los cuales describo al final._
[Ajustes a JSONFox.pdf](https://github.com/Irwin1985/JSONFox/files/15181734/Ajustes.a.JSONFox.pdf)

1. Para ejecutar .Parse adecuadamente con un JSON que me llega en UTF8, debo convertirlo a ANSI antes de entregárselo a JSONFox.

2. Si utilizo .NetScanner=.t. no es imperativo convertirlo a UTF8.
   Pero dado que con .NetScanner=.t. necesitamos la JSONFoxHelper.dll, pues inicialmente quiero mirar otras alternativas, pues lo más probable es que para 64 bits necesite ser recompilada.
   
3. Si utilizo .JScriptScanner=.t. no es imperativo convertirlo a UTF8.
   Y me doy cuenta que con .JScriptScanner=.t. no necesitamos una .dll, es muy probable que sí pueda usarlo en 64 bits (ésto se debe verificar).
   
Adjunto el (1) sample_H.prg, (2) una imagen con el resultado final, y (3) un doc donde describo los ajustes que debí hacer a JONFox, para que Irwin los analice y los implemente de una mejor forma en la distrib final.

![image](https://github.com/Irwin1985/JSONFox/assets/5818845/bc5500c0-9d16-4d1d-a289-df58d2bc6dbe)

![image](https://github.com/Irwin1985/JSONFox/assets/5818845/44b68739-97bc-44a6-be4f-e73a67951366)

![image](https://github.com/Irwin1985/JSONFox/assets/5818845/dddcf20d-9171-4d43-b704-01b91ae242d3)

[Ajustes a JSONFox.pdf](https://github.com/Irwin1985/JSONFox/files/15181751/Ajustes.a.JSONFox.pdf)
[mensaje.txt](https://github.com/Irwin1985/JSONFox/files/15181756/mensaje.txt)
[Ajustes.txt](https://github.com/Irwin1985/JSONFox/files/15181757/Ajustes.txt)
[sample_H_enviar.zip](https://github.com/Irwin1985/JSONFox/files/15181779/sample_H_enviar.zip)

**Comment by Irwin1985** [comment]
Hola @jhernancanom 

> 1. Para ejecutar .Parse adecuadamente con un JSON que me llega en UTF8, debo convertirlo a ANSI antes de entregárselo a JSONFox. **Ok**

> 2. Si utilizo .NetScanner=.t. no es imperativo convertirlo a UTF8.
> Pero dado que con .NetScanner=.t. necesitamos la JSONFoxHelper.dll, pues inicialmente quiero mirar otras alternativas, pues lo más probable es que para 64 bits necesite ser recompilada. **Correcto**

> 3. Si utilizo .JScriptScanner=.t. no es imperativo convertirlo a UTF8.
> Y me doy cuenta que con .JScriptScanner=.t. no necesitamos una .dll, es muy probable que sí pueda usarlo en 64 bits (ésto se debe verificar). **MSSCRIPT.OCX tiene su versión para 64 bit así que sospecho que funciona también**

puedes compartir tu JSON (C:\MyDir\MyFile.json) para hacer pruebas?

**Comment by jhernancanom** [comment]
Hola, Daniel.
Sí me estaba afectando.

Y la corrección que comentas es parte de lo que le reporto a Irwin en el Ajustes.PDF; pero las atribuciones son para vos porque efectivamente usate GitHub.
Es muy conveniente saber usar GitHub.

> No creo que esto sea la causa del error reportado aquí, pero hice esta corrección en el código y estoy creando un Pull Request para actualizar el master. Después de la actualización, puedes realizar la prueba nuevamente. ![image](https://private-user-images.githubusercontent.com/89362488/327751402-41f44f91-2255-431b-ac2f-49a954511278.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3NjczNDcsIm5iZiI6MTcxNDc2NzA0NywicGF0aCI6Ii84OTM2MjQ4OC8zMjc3NTE0MDItNDFmNDRmOTEtMjI1NS00MzFiLWFjMmYtNDlhOTU0NTExMjc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAzVDIwMTA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxNzVkM2FmNmIwOTNlMjY5M2VmYzQ2NDZmNzA1NWZhZDc3MjA0ZWU4ZWQwZjg4YTY4NmRmN2EwMGUzOGI2MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fORIItkH5toySSPLCvZlOe-D9F81tFeZcbSnQtd8n0c)

**Comment by DanielCarlos231** [comment]
Lo siento, debo decir que no leí el archivo PDF que enviaste.

Resulta que me encontré con este problema yo mismo.

Pero ahora acabo de revisar tu archivo PDF y hice los ajustes que sugeriste, hice un Pull Request en la rama principal, solo tenemos que esperar a que Irwin lo fusione.

> Hola, Daniel. Sí me estaba afectando.
> 
> Y la corrección que comentas es parte de lo que le reporto a Irwin en el Ajustes.PDF; pero las atribuciones son para vos porque efectivamente usate GitHub. Es muy conveniente saber usar GitHub.
> 
> > No creo que esto sea la causa del error reportado aquí, pero hice esta corrección en el código y estoy creando un Pull Request para actualizar el master. Después de la actualización, puedes realizar la prueba nuevamente. ![image](https://private-user-images.githubusercontent.com/89362488/327751402-41f44f91-2255-431b-ac2f-49a954511278.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3NjczNDcsIm5iZiI6MTcxNDc2NzA0NywicGF0aCI6Ii84OTM2MjQ4OC8zMjc3NTE0MDItNDFmNDRmOTEtMjI1NS00MzFiLWFjMmYtNDlhOTU0NTExMjc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAzVDIwMTA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxNzVkM2FmNmIwOTNlMjY5M2VmYzQ2NDZmNzA1NWZhZDc3MjA0ZWU4ZWQwZjg4YTY4NmRmN2EwMGUzOGI2MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fORIItkH5toySSPLCvZlOe-D9F81tFeZcbSnQtd8n0c)

**Comment by jhernancanom** [comment]
¿Y los otros ajustes, el de (1) comentar _ClipText en ScanTokens, y el de (2) set procedure to --quizá-- en la JsonClass?


> Lo siento, debo decir que no leí el archivo PDF que enviaste.
> 
> Resulta que me encontré con este problema yo mismo.
> 
> Pero ahora acabo de revisar tu archivo PDF y hice los ajustes que sugeriste, hice un Pull Request en la rama principal, solo tenemos que esperar a que Irwin lo fusione.
> 
> > Hola, Daniel. Sí me estaba afectando.
> > Y la corrección que comentas es parte de lo que le reporto a Irwin en el Ajustes.PDF; pero las atribuciones son para vos porque efectivamente usate GitHub. Es muy conveniente saber usar GitHub.
> > > No creo que esto sea la causa del error reportado aquí, pero hice esta corrección en el código y estoy creando un Pull Request para actualizar el master. Después de la actualización, puedes realizar la prueba nuevamente. ![image](https://private-user-images.githubusercontent.com/89362488/327751402-41f44f91-2255-431b-ac2f-49a954511278.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3NjczNDcsIm5iZiI6MTcxNDc2NzA0NywicGF0aCI6Ii84OTM2MjQ4OC8zMjc3NTE0MDItNDFmNDRmOTEtMjI1NS00MzFiLWFjMmYtNDlhOTU0NTExMjc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAzVDIwMTA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxNzVkM2FmNmIwOTNlMjY5M2VmYzQ2NDZmNzA1NWZhZDc3MjA0ZWU4ZWQwZjg4YTY4NmRmN2EwMGUzOGI2MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fORIItkH5toySSPLCvZlOe-D9F81tFeZcbSnQtd8n0c)

**Comment by jhernancanom** [comment]
Negativo el civil.....
Sólo tiene esas dos caracteristicas (1) es grande --aunq no creo q sea el problema--, (2) está en UTF8, q creo q es lo q causa el impasse.

> Hola @jhernancanom
> 
> puedes compartir tu JSON (C:\MyDir\MyFile.json) para hacer pruebas?

**Comment by DanielCarlos231** [comment]
Realicé estos también, solo falta que Irwin haga el merge.
Pero el SET Procedure lo coloqué en el loader.prg.

> ¿Y los otros ajustes, el de (1) comentar _ClipText en ScanTokens, y el de (2) set procedure to --quizá-- en la JsonClass?

**Comment by Irwin1985** [comment]
Integrados los cambios, gracias @jhernancanom  y @DanielCarlos231 por la ayuda.
