### ISSUE TITLE
Preg2: Sobre JSONViewer en x64

### ISSUE THREAD

**Issue by jhernancanom** [Irwin1985/JSONFox#6]
Preg2: Sobre JSONViewer en x64
----------------------------------------

Hola, Irwin.

Te muestro algo sobre el uso de tu clase en x64.

He ejecutado el ejemplo de la función .JSONViewer() en x64, con el VFPA x64.
Pero como la función .JSONViewer() está basada en un form con un control RTF (OCX), entonces no funciona.

Le hice algunas modificaciones al formulario para usar un control EditBox nativo, en vez del RTF, y logré hacerlo funcionar.

Te adjunto mi solución, para que verifiques si se puede mejorar y/o integrar mejor. Si necesitas que diseñe un sólo form que pueda ser usado en ambos ambientes utilizando esta metodología, con gusto.

[frmJSONViewer-x64.zip](https://github.com/Irwin1985/JSONFox/files/5900591/frmJSONViewer-x64.zip)

**Comment by Irwin1985** [comment]
Vale, lo tendré en mente para integrarlo para x64. Gracias!
