### ISSUE TITLE
Apuntes

### ISSUE THREAD

**Issue by jhernancanom** [Irwin1985/JSONFox#7]
----------------------------------------
imagen01
- Hay dos partes donde se habla de la función Signature.

imagen02
- La indentación de varios métodos en la ayuda está incorrecta: debe aparecer hacia la izquierda y con ícono negro (se muestran sólo dos).
----------------------------------------
![imagen01](https://user-images.githubusercontent.com/5818845/106398416-a65f0000-63e0-11eb-94dd-73ac035bcec4.png)
![imagen02](https://user-images.githubusercontent.com/5818845/106398421-a828c380-63e0-11eb-929c-3a28314716d5.png)

**Comment by Irwin1985** [comment]
Vale, gracias por notarlo, ya lo voy a revisar. **Function Signature** no es una función sino las firmas de las funciones documentadas, lo he cambiado por **Full Documentation**.
