### ISSUE TITLE
Error While parsing Date with Time. Return empty date

### ISSUE THREAD

**Issue by RightOpen** [Irwin1985/JSONFox#8]
`Do LocFile("JSONFox", "app")
Text To lcJsonStr NoShow
   {
    "name":"Irwin",
    "surname": "Rodriguez",
    "birth":"2021-02-18 19:45:58",
    "current_year": 2019,
    "wife": "Serelys Fonseca",
    "music_band":"The Beatles",
    "size": 1.79,
    "isgamer": false,
    "isprogrammer": true, 
    "hascar": null
   }
 EndText
obj = _Screen.Json.Parse(lcJsonStr)
 
 * Don't forget check the LastErrorText
 If _Screen.Json.lError
   MessageBox(_Screen.Json.LastErrorText, 48, "Something went wrong")
   Return
 EndIf

?obj.birth  
**Return empty Date    .  .   :   :   AM **

`

**Comment by Irwin1985** [comment]
You're right! I'll be working on it. thanks for the feed!

**Comment by Irwin1985** [comment]
fixed bug. including ISO 8601 and JavaScript built-in date & date time format.
