### ISSUE TITLE
date format

### ISSUE THREAD

**Issue by rromero1956** [Irwin1985/JSONFox#9]
Hi
primero, un trabajo my bueno

Lo unico que me causo un poco de problema fueron con los date format data elements

como test data usa est json file: (real data format) 
{
	"customerId": "ADV00000",
	"typeOfService": "AII",
	"serviceTypeCode": "",
	"transactionId": "ADV00000573a1fc436d14cac",
	"statusCode": "AIR-I-1100",
	"codeType": "AIRIBU",
	"message": "Your request was successfully processed.",
	"individualDetails": {
		"individualIdentifier": "frnk6e9TwSYX8Xd6qvDFYQkYM0QNtUZZYL3ZyfduqqnZTsPf3D8yA-1uu6f3SECHE28gWS6T_tENlOFdR932e6HvbRMdKD-qEXrek5sV1ej2OY_92X9U6Q==",
		"individual": {
			"personalDetails": {
				"dateOfBirth": "16041964",
				"lastName": "MILGATE",
				"firstName": "NATALIE"
			},
			"medicareCard": {
				"medicareCardNumber": "5951024371",
				"medicareIRN": "1"
			},
			"address": {
				"addressLineOne": "118 JOHN CT",
				"addressLineTwo": "",
				"locality": "AMYTON",
				"postCode": "5431"
			}
		},
		"catchupDate": "",
		"indigenousStatus": false,
		"additionalVaccineIndicator": false,
		"medContraindicationIndicator": false,
		"naturalImmunityIndicator": false,
		"vaccineTrialIndicator": false,
		"actionRequiredIndicator": false
	}
}
como vez  el "statusCode" y "individualIdentifier" apesar de no ser un date format returna "  /  /  " como si fuera a date
Viendo tu code solo estas chequeando si hay 2 o mas "-", pero como vez en mi case no es suficiente
abri el project y modifique (append)  lo siguiente:

If Occurs('-', lvNewVal) >= 2 and inlist(val(strextract(lvNewVal,"-","-")),1,2,3,4,5,6,7,8,9,10,11,12) and len(strextract(lvNewVal,"-","-"))=<2

ahora no solo chequea la existancia de 2 o mas "-" pero tambien chequea que el valor sea entre 1 a 12 (month)
Hay varias areas que tiene que hacerce la misma modification 
Posiblement hay otras maneras the hacer la misma cosa, por el momento esto trabaja para my

Muchas gracias por esta herramienta

Romer

**Comment by Irwin1985** [comment]
Hola Romer, tienes razón. Tenia ese tema de reconocimiento de fechas pendiente para arreglar ya que la solución inicial no me convencia mucho, pues ha llegado el momento de corregirlo. He creado una función que reconoce formatos de fecha usando expresiones regulares, una vez que el string sea reconocido como fecha entonces pasará a la función DateFormat de JSONUtils, de lo contrario se devuelve tal cual como vino.

Ya puedes descargar el fuente y la app. Prueba para ver si todo funciona correctamente.

Saludos!
